config/routes.rb
Rails.application.routes.draw do
resources :articles
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 def index
    @articles = Article.all
  end
def show
    @article = Article.find(params[:id])
  end
 
 def new
  @article = Article.new
end
 def edit
  @article = Article.find(params[:id])
end
def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end
def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end
 

	private
  def article_params
    params.require(:article).permit(:title, :text)
  end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>SignUp Page</h1>
<%= form_for :article   do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name %> <br />
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email%> <br />
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %> <br />
</p>
<p>
  <%= f.label :confirm_password %>
  <%= f.password_field :confirm_password %> <br />
</p>
<p>
  <%= f.submit "Login account" %>
</p>
<% end %>

app/views/articles/new.html.erb
<h1>Login</h1>
<%= form_for :article, url: articles_path do |f| %>
 

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :text %>
  </p>
 
  <p>
    <%= f.submit "Login" %>
  </p>

<%= link_to 'signup', articles_path %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qwerty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Hello, Rails </h1>
<%= link_to 'qwerty', controller: 'articles' %>